ifneq ($(wildcard /usr/lib/erlang),)
  ERLANG_ROOT=/usr/lib/erlang
else
  ifneq ($(wildcard /Library/DarwinPorts/lib/erlang),)
    ERLANG_ROOT=/Library/DarwinPorts/lib/erlang
  endif
endif
ifneq ($(wildcard lib/eunit*),)
  EUNIT_ROOT=$(wildcard lib/eunit*)
else
  ifneq ($(wildcard ../eunit),)
    EUNIT_ROOT=../eunit
  endif
endif
